/** Barrel — import from @/lib/tenant for all tenant resolution. */
export {
  getTenantBySlug,
  findMappedTenantsForUser,
  validateActiveTenantCookie,
  resolveTenantForDashboard,
  getActiveTenantCookie,
  setActiveTenantCookie,
  clearActiveTenantCookies,
  applyActiveTenantCookieToResponse,
  requireActiveTenantForActions,
  readTenantIdHintFromForm,
  ACTIVE_TENANT_COOKIE_NAME,
  ACTIVE_TENANT_FORM_FIELD,
  pickActiveTenant,
  redirectWithActiveTenant,
  tenantIdFromMutation,
  type MappedTenant,
  type TenantResolutionResult,
  type TenantResolutionSource,
  type ActiveTenantActionContext,
  type ActiveTenantActionResult,
  type TenantActionOptions,
} from "./tenant/index";
